sign-commit                = true
sign-tag                   = true
tag-prefix                 = "toys-"
pre-release-replacements = [
    {file ="Cargo.toml", search="version = \"[a-z0-9\\.-]+\"", replace="version = \"{{version}}\""},
]