[package]
name = "parsing-rust"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4.14"
regex = "0.1"

[dev-dependencies]
anyhow = "1.0.44"
env_logger = "0.9.0"
prop-check-rs = "0.0.4"