sign-commit                = false
sign-tag                   = false
pre-release-commit-message = "chore: bump version"
dev-version                = false
tag-message                = "{{tag_name}}"
tag-name                   = "{{prefix}}v{{version}}"
consolidate-commits        = false
consolidate-pushes         = true
allow-branch               = ["main"]