sign-commit                = true
sign-tag                   = true
tag-prefix                 = "uri-"
tag-message                = "Bump version to v{{version}}"
pre-release-replacements = [
    {file ="Cargo.toml", search="version = \"[a-z0-9\\.-]+\"", replace="version = \"{{version}}\""},
]