consolidate-commits        = true
pre-release-commit-message = "Prepare to release"
tag-message                = "Bump version to v{{version}}"
tag-prefix                 = "uri:"
dependent-version          = "upgrade"