[package]
name = "oni-comb-parser-rs"
version = "0.0.46"
edition = "2021"
description = "A Rust crate for parser combinators"
license = "MIT OR Apache-2.0"
keywords = [ "parser", "combinator" ]
categories = [ "parsing" ]
readme = "README.md"
repository = "https://github.com/j5ik2o/oni-comb-rs"

[badges.github]
repository = "j5ik2o/oni-comb-rs"
workflow = "Rust"

[dependencies]
log = "0.4.17"
regex = "1.7"

[dev-dependencies]
anyhow = "1.0.70"
env_logger = "0.10.0"
prop-check-rs = "0.0.160"
rust_decimal = "1.29.1"
chrono = "0.4.24"
pom = "3.2.0"
nom = "7.1.3"
criterion = { version = "0.4.0", features = [ "html_reports" ]}
ctor = "0.1.26"
pprof = { version = "0.11", features = ["flamegraph", "criterion"] }

[[bench]]
name = "bench_main"
harness = false
