[package]
name = "oni-comb-parser-rs"
version = "0.0.204"
edition = "2021"
description = "A Rust crate for parser combinators"
license = "MIT OR Apache-2.0"
keywords = [ "parser", "combinator" ]
categories = [ "parsing" ]
readme = "README.md"
repository = "https://github.com/j5ik2o/oni-comb-rs"

[badges.github]
repository = "j5ik2o/oni-comb-rs"
workflow = "Rust"

[dependencies]
log = "0.4.20"
regex = "1.9"

[dev-dependencies]
anyhow = "1.0.75"
env_logger = "0.10.0"
prop-check-rs = "0.0.318"
rust_decimal = "1.32.0"
chrono = "0.4.28"
pom = "3.3.0"
nom = "7.1.3"
criterion = { version = "0.5.1", features = [ "html_reports" ]}
ctor = "0.2.4"
pprof = { version = "0.12", features = ["flamegraph", "criterion"] }

[[bench]]
name = "bench_main"
harness = false
