[package]
name = "oni-comb-parser-rs"
version = "0.0.309"
edition = "2021"
description = "A Rust crate for parser combinators"
license = "MIT OR Apache-2.0"
keywords = [ "parser", "combinator" ]
categories = [ "parsing" ]
readme = "README.md"
repository = "https://github.com/j5ik2o/oni-comb-rs"

[badges.github]
repository = "j5ik2o/oni-comb-rs"
workflow = "Rust"

[dependencies]
log = "0.4.20"
regex = "1.10"

[dev-dependencies]
anyhow = "1.0.78"
env_logger = "0.10.1"
prop-check-rs = "0.0.441"
rust_decimal = "1.33.1"
chrono = "0.4.31"
pom = "3.3.0"
nom = "7.1.3"
criterion = { version = "0.5.1", features = [ "html_reports" ]}
ctor = "0.2.6"
pprof = { version = "0.13", features = ["flamegraph", "criterion"] }

[[bench]]
name = "bench_main"
harness = false
