mod authority_parsers;
mod basic_parsers;
mod fragment_parsers;
mod hier_part_parsers;
mod host_parsers;
mod ip_v4_address_parsers;
mod ip_v6_address_parsers;
mod path_parsers;
mod port_parsers;
mod query_parsers;
mod scheme_parsers;
pub mod uri_parsers;
mod user_info_parsers;
