name: release-uri
on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: true
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-release
        version: "0.21.1"
    - name: release
      run: |
        git config user.name "Junichi Kato"
        git config user.email j5ik2o@gmail.com
        cargo release --token ${{ secrets.CARGO_TOKEN }} \
          --execute --verbose --no-confirm \
          -p oni-comb-crond-rs patch
